<!DOCTYPE html>
<html lang="de-DE" prefix="og: https://ogp.me/ns#" xmlns:og="http://opengraphprotocol.org/schema/">
    <head>
        <?php
            include_once realpath($_SERVER["DOCUMENT_ROOT"])."/sites/head.html"
        ?>
        <title>Fächer - Friedrich-Gymnasium Luckenwalde</title>
        <link rel="stylesheet" href="/new-css/faecher.css">
    </head>
    <body>
            <?php include_once realpath($_SERVER["DOCUMENT_ROOT"])."/sites/header.html" ?>
            <!-- TODO: add hrefs to faecher pages + missing icons -->
            <section class="faecher">
                <div class="bereichdiv">
                    <label class="fachbereich">Sprachwissenschaften</label><br>
                    <ul class="faecherlist">
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://freesvg.org/stack-of-books-vector-clip-art" class="imgsource">https://freesvg.org/stack-of-books-vector-clip-art</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Deutsch.svg" class="fachimg"><br><span>Deutsch</span></div></li></a> <!-- https://freesvg.org/stack-of-books-vector-clip-art -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://en.wikipedia.org/wiki/File:English_language.svg" class="imgsource">https://en.wikipedia.org/wiki/File:English_language.svg</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Englisch.svg" class="fachimg"><br><span>Englisch</span></div></li></a> <!-- https://en.wikipedia.org/wiki/File:English_language.svg -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://commons.wikimedia.org/wiki/File:France_flag_waving_icon.svg" class="imgsource">https://commons.wikimedia.org/wiki/File:France_flag_waving_icon.svg</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Französisch.svg" class="fachimg"><br><span>Französisch</span></div></li></a> <!-- https://commons.wikimedia.org/wiki/File:France_flag_waving_icon.svg -->
                        <!-- <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="" class="fachimg"><br><span>Polnisch</span></div></li></a> -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://freesvg.org/flag-of-the-russian-federation-vector-graphics" class="imgsource">https://freesvg.org/flag-of-the-russian-federation-vector-graphics</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Russisch.svg" class="fachimg"><br><span>Russisch</span></div></li></a> <!-- https://freesvg.org/flag-of-the-russian-federation-vector-graphics -->
                        <!-- <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="" class="fachimg"><br><span>Spanisch</span></div></li></a> -->
                        <!-- <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="" class="fachimg"><br><span>Türkisch</span></div></li></a> -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/161704.html" class="imgsource">https://svgsilh.com/image/161704.html</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Latein.svg" class="fachimg"><br><span>Latein</span></div></li></a> <!-- https://svgsilh.com/image/161704.html -->
                    </ul>
                </div>
                <div class="bereichdiv">
                    <label class="fachbereich">Naturwissenschaften</label><br>
                    <ul class="faecherlist">
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://de.wikipedia.org/wiki/Datei:Math.svg" class="imgsource">https://de.wikipedia.org/wiki/Datei:Math.svg</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Mathematik.svg" class="fachimg"><br><span>Mathematik</span></div></li></a> <!-- https://de.wikipedia.org/wiki/Datei:Math.svg -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://www.labbe.de/blog/Ruth-Patrick" class="imgsource">https://www.labbe.de/blog/Ruth-Patrick</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Biologie.svg" class="fachimg"><br><span>Biologie</span></div></li></a> <!-- https://www.labbe.de/blog/Ruth-Patrick -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/de/image/1073363.html" class="imgsource">https://svgsilh.com/de/image/1073363.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Chemie-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Chemie.svg" class="fachimg"></picture><br><span>Chemie</span></div></li></a> <!-- https://svgsilh.com/de/image/1073363.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/de/image/148441.html" class="imgsource">https://svgsilh.com/de/image/148441.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Physik-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Physik.svg" class="fachimg"></picture><br><span>Physik</span></div></li></a> <!-- https://svgsilh.com/de/image/148441.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://www.svgrepo.com/svg/28224/programming" class="imgsource">https://www.svgrepo.com/svg/28224/programming</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Informatik-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Informatik.svg" class="fachimg"></picture><br><span>Informatik</span></div></li></a> <!-- https://www.svgrepo.com/svg/28224/programming -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/2099128.html" class="imgsource">https://svgsilh.com/image/2099128.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Naturwissenschaften-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Naturwissenschaften.svg" class="fachimg"></picture><br><span>Naturwissenschaften</span></div></li></a> <!-- https://svgsilh.com/image/2099128.html -->
                    </ul>
                </div>
                <div class="bereichdiv">
                    <label class="fachbereich">Gesellschaftswissenschaften</label><br>
                    <ul class="faecherlist">
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/158348.html" class="imgsource">https://svgsilh.com/image/158348.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Erdkunde-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Erdkunde.svg" class="fachimg"></picture><br><span>Erdkunde</span></div></li></a> <!-- https://svgsilh.com/image/158348.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/33963.html" class="imgsource">https://svgsilh.com/image/33963.html</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Geschichte.svg" class="fachimg"><br><span>Geschichte</span></div></li></a> <!-- https://svgsilh.com/image/33963.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/32310.html" class="imgsource">https://svgsilh.com/image/32310.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/PB-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/PB.svg" class="fachimg"></picture><br><span>Politische Bildung</span></div></li></a> <!-- https://svgsilh.com/image/32310.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://publicdomainvectors.org/en/vectoriales-gratuitas/Diosa-de-la-justicia-signo-vector-de-la-imagen/16404.html" class="imgsource">https://publicdomainvectors.org/en/vectoriales-gratuitas/Diosa-de-la-justicia-signo-vector-de-la-imagen/16404.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Gesellschaftswissenschaften-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Gesellschaftswissenschaften.svg" class="fachimg"></picture><br><span>Gesellschaftswissenschaften</span></div></li></a> <!-- https://publicdomainvectors.org/en/vectoriales-gratuitas/Diosa-de-la-justicia-signo-vector-de-la-imagen/16404.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://commons.wikimedia.org/wiki/File:Religion_icon.svg" class="imgsource">https://commons.wikimedia.org/wiki/File:Religion_icon.svg</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/RE-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/RE.svg" class="fachimg"></picture><br><span>Religion</span></div></li></a> <!-- https://commons.wikimedia.org/wiki/File:Religion_icon.svg -->
                        <!-- <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Eva_RE.svg" class="fachimg"><br><span>Evangelischer Religionsunterricht</span></div></li></a>
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Kat_RE.svg" class="fachimg"><br><span>Katholischer Religionsunterricht</span></div></li></a> -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://unterrichten.zum.de/index.php?title=Datei:Buch-Icon.svg&veaction=edit&redlink=1" class="imgsource">https://unterrichten.zum.de/index.php?title=Datei:Buch-Icon.svg&veaction=edit&redlink=1</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/LER-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/LER.svg" class="fachimg"></picture><br><span>Lebensgestaltung-Ethik-Religionskunde</span></div></li></a> <!-- https://unterrichten.zum.de/index.php?title=Datei:Buch-Icon.svg&veaction=edit&redlink=1 -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://commons.wikimedia.org/wiki/File:Euro_sign.svg" class="imgsource">https://commons.wikimedia.org/wiki/File:Euro_sign.svg</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/WAT-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/WAT.svg" class="fachimg"></picture><br><span>Wirtschaft-Arbeit-Technik<br>Wirtschaftswissenschaften</span></div></li></a> <!-- https://commons.wikimedia.org/wiki/File:Euro_sign.svg -->
                        <!-- <a><li class="fach"><figcaption>i</figcaption><object><a href="" class="imgsource"></a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Wirtschaft.svg" class="fachimg"><br><span>Wirtschaftswissenschaften</span></div></li></a> -->
                    </ul>
                </div>
                <div class="bereichdiv">
                    <label class="fachbereich">Künstlerische Fächer</label><br>
                    <ul class="faecherlist">
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://www.ardenne-gymnasium.de/media/icon_darstellendes_spiel.svg" class="imgsource">https://www.ardenne-gymnasium.de/media/icon_darstellendes_spiel.svg</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/DS-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/DS.svg" class="fachimg"></picture><br><span>Darstellendes Spiel</span></div></li></a> <!-- https://www.ardenne-gymnasium.de/media/icon_darstellendes_spiel.svg -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://publicdomainvectors.org/de/kostenlose-vektorgrafiken/Pinsel-Paletten/40255.html" class="imgsource">https://publicdomainvectors.org/de/kostenlose-vektorgrafiken/Pinsel-Paletten/40255.html</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Kunst.svg" class="fachimg"><br><span>Kunst</span></div></li></a> <!-- https://publicdomainvectors.org/de/kostenlose-vektorgrafiken/Pinsel-Paletten/40255.html -->
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/2073069.html" class="imgsource">https://svgsilh.com/image/2073069.html</a class="imgsource"></object><div><picture><source srcset="/files/site-ressources/faecher-icons/Musik-Dark.svg" media="(prefers-color-scheme: dark)"><img src="/files/site-ressources/faecher-icons/Musik.svg" class="fachimg"></picture><br><span>Musik</span></div></li></a> <!-- https://svgsilh.com/image/2073069.html -->
                    </ul>
                </div>
                <div class="bereichdiv">
                    <label class="fachbereich">Sonstige</label><br>
                    <ul class="faecherlist">
                        <a><li class="fach"><figcaption>i</figcaption><object><a href="https://svgsilh.com/image/309539.html" class="imgsource">https://svgsilh.com/image/309539.html</a class="imgsource"></object><div><img src="/files/site-ressources/faecher-icons/Sport.svg" class="fachimg"><br><span>Sport</span></div></li></a> <!-- https://svgsilh.com/image/309539.html -->
                    </ul>
                </div>
            </section>
            <?php include_once realpath($_SERVER["DOCUMENT_ROOT"])."/sites/footer.html" ?>
    </body>
</html>